offre:
    path:     /
    defaults: { _controller: "FrontRealBundle:Offre:index" }

offre_show:
    path:     /{id}/show
    defaults: { _controller: "FrontRealBundle:Offre:show" }

offre_new:
    path:     /new
    defaults: { _controller: "FrontRealBundle:Offre:new" }

offre_create:
    path:     /create
    defaults: { _controller: "FrontRealBundle:Offre:create" }
    requirements: { _method: post }

offre_edit:
    path:     /{id}/edit
    defaults: { _controller: "FrontRealBundle:Offre:edit" }

offre_update:
    path:     /{id}/update
    defaults: { _controller: "FrontRealBundle:Offre:update" }
    requirements: { _method: post|put }

offre_delete:
    path:     /{id}/delete
    defaults: { _controller: "FrontRealBundle:Offre:delete" }
    requirements: { _method: post|delete }
