Ville:
    type: entity
    table: ville
    id:
        ville:
            type: string
            nullable: false
            length: 25
            fixed: false
            comment: ''
            id: true
            generator:
                strategy: IDENTITY
    lifecycleCallbacks: {  }
